description: >
  A Ubuntu based docker image created by CircleCI
docker:
  - image: 'cimg/base:2023.12'
parameters:
  tag:
    default: lts
    description: >
      Pick a specific cimg/node image variant:
      https://hub.docker.com/r/cimg/node/tags
    type: string
